### ISSUE TITLE
I cannot run ‘test_led.py'

### ISSUE THREAD

**Issue by alphaizm** [Seeed-Studio/Seeed_Python_ReTerminal#6]
# Execution result.

I tried to run test_led.py, it produced an error.

`python test_led.py
`

> STA ON, USR OFF
Traceback (most recent call last):
  File "/home/pi/Downloads/Seeed_Python_ReTerminal/samples/test_led.py", line 7, in <module>
    rt.sta_led = True
  File "/usr/local/lib/python3.9/dist-packages/seeed_python_reterminal/core.py", line 41, in sta_led
    self.sta_led_green = value
  File "/usr/local/lib/python3.9/dist-packages/seeed_python_reterminal/core.py", line 50, in sta_led_green
    self.__write_to_file(_Core.__STA_LED_GREEN_BRIGHTNESS, "1" if value else "0")
  File "/usr/local/lib/python3.9/dist-packages/seeed_python_reterminal/core.py", line 147, in __write_to_file
    with open(file_name, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/leds/usr_led2/brightness'

# My environment.

![image](https://github.com/Seeed-Studio/Seeed_Python_ReTerminal/assets/46560526/707cca51-c8de-486a-a15d-8f6740149fbb)

**Comment by matsujirushi** [comment]
Try running it with `sudo`.

```
sudo python test_led.py
```
